name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to Raspberry Pi and start server
        run: |
          ssh  -o StrictHostKeyChecking=no salman@59.182.0.211 'cd ~/my-node-app && git pull origin main && npm install && node index.js'
