name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
  
    runs-on: ubuntu-latest

    steps:
      - name: SSH and run commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            # Identify the existing Node.js process and kill it
            existing_pid=$(lsof -i :4000 -t)
            if [ -n "$existing_pid" ]; then
            echo "Stopping existing Node.js server with PID $existing_pid"
            kill -9 "$existing_pid"
            fi

            cd ~/my-node-app && git pull origin main && npm install && node index.js
      

