name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
  
    runs-on: ubuntu-latest

    steps:
      - name: SSH and run commands
        uses: appleboy/ssh-action@master
        with:
          host: 59.182.0.211
          username: salman
          password: Namlas@786
          port: 22
          run: |
           cd ~/my-node-app && git init && git remote add origin git@github.com:user/repo.git && git pull origin main && npm install && pm2 restart your-app
      

